# Generated by Django 3.1.7 on 2021-04-06 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose')),
                ('category', models.CharField(max_length=50, verbose_name='Type')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Appointment Date')),
                ('booking_date', models.DateTimeField(verbose_name='Booking Date')),
                ('follow_up_date', models.DateTimeField(null=True, verbose_name='Follow Up')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Doctors', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('title', models.CharField(default='Dr.', max_length=200, verbose_name='Title')),
                ('phone_no', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('d_o_b', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('biography', models.CharField(blank=True, max_length=1000, verbose_name='Biography')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='County')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Town')),
                ('pricing', models.FloatField(default=0.0, verbose_name='Amount')),
                ('services', models.CharField(blank=True, max_length=1000, verbose_name='Services')),
                ('specialization', models.CharField(blank=True, max_length=1000, verbose_name='Specialization')),
                ('clinic', models.CharField(blank=True, max_length=100, verbose_name='Clinic')),
                ('clinic_address', models.CharField(blank=True, max_length=100, verbose_name='Clinic Address')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, verbose_name='Day')),
                ('interval', models.IntegerField(verbose_name='Interval')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Patient/Profile/', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('d_o_b', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone_no', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('blood_group', models.CharField(max_length=5, verbose_name='Blood Group')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('county', models.CharField(max_length=50, verbose_name='County')),
                ('town', models.CharField(max_length=50, verbose_name='Town')),
                ('street_lane', models.CharField(max_length=50, verbose_name='Street/Lane')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(max_length=500, upload_to='Image/Speciality', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctorschedule')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('pinterest_url', models.URLField(blank=True, verbose_name='Pinterest URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Linkedin URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Youtube URL')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Review Title')),
                ('text', models.CharField(blank=True, max_length=150, verbose_name='Review Title')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('text', models.CharField(max_length=150, verbose_name='Review Title')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Year')),
                ('registration', models.CharField(max_length=50, verbose_name='Registration')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Prescription Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('quantity', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('days', models.FloatField(default=0.0, verbose_name='Prescription Days')),
                ('morning', models.BooleanField(default=False, verbose_name='Morning')),
                ('afternoon', models.BooleanField(default=False, verbose_name='Afternoon')),
                ('evening', models.BooleanField(default=False, verbose_name='Evening')),
                ('night', models.BooleanField(default=False, verbose_name='Night')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=50, verbose_name='Membership')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(verbose_name='Record Date')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('attachment', models.FileField(blank=True, upload_to='File/Patient/MedicalRecords/', verbose_name='Attachment')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LikedReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.BooleanField(default=False, verbose_name='Recommend')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikedReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.BooleanField(default=False, verbose_name='Recommend')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('date_paid', models.DateTimeField(auto_now_add=True, verbose_name='Paid On')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50, verbose_name='Hospital Name')),
                ('start', models.DateField(verbose_name='From')),
                ('finish', models.DateField(blank=True, verbose_name='To')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50, verbose_name='Degree')),
                ('institute', models.CharField(max_length=50, verbose_name='College/Institute')),
                ('y_o_c', models.DateField(verbose_name='Year of Completion')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.speciality'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Name')),
                ('quantity', models.FloatField(default=1.0, verbose_name='Prescription Days')),
                ('vat', models.FloatField(default=0.0, verbose_name='V.A.T')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('appointment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=50, verbose_name='Award')),
                ('year', models.DateField(verbose_name='Year')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient'),
        ),
    ]
