# Generated by Django 3.1.7 on 2021-04-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='review',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='Recommend'),
        ),
    ]
