# Generated by Django 3.1.7 on 2021-04-06 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, max_length=500, upload_to='Image/Setting', verbose_name='Website Logo')),
                ('name', models.CharField(max_length=50, verbose_name='Website Name')),
                ('icon', models.ImageField(blank=True, max_length=500, upload_to='Image/Setting', verbose_name='Favicon')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Administrator', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('d_o_b', models.DateField(verbose_name='Date of Birth')),
                ('phone_no', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('address_line', models.CharField(blank=True, max_length=200, verbose_name='Address Line')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='County')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Town')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
