# Generated by Django 3.1.7 on 2021-02-25 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Patient/Profile/', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('d_o_b', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone_no', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('blood_group', models.CharField(max_length=5, verbose_name='Blood Group')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('county', models.CharField(max_length=50, verbose_name='County')),
                ('town', models.CharField(max_length=50, verbose_name='Town')),
                ('street_lane', models.CharField(max_length=50, verbose_name='Street/Lane')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
