# Generated by Django 3.1.7 on 2021-03-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_socialmedia'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose')),
                ('category', models.CharField(max_length=50, verbose_name='Type')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Appointment Date')),
                ('booking_date', models.DateTimeField(verbose_name='Booking Date')),
                ('follow_up_date', models.DateTimeField(blank=True, verbose_name='Follow Up')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
