# Generated by Django 3.1.7 on 2021-03-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_socialmedia'),
        ('patients', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('date_paid', models.DateTimeField(verbose_name='Paid On')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Name')),
                ('quantity', models.FloatField(default=1.0, verbose_name='Prescription Days')),
                ('vat', models.FloatField(default=0.0, verbose_name='V.A.T')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('appointment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patients.appointment')),
                ('invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patients.invoice')),
            ],
        ),
    ]
