# Generated by Django 3.1.7 on 2021-03-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210320_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateTimeField(null=True, verbose_name='Follow Up'),
        ),
    ]
