# Generated by Django 3.1.7 on 2021-03-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_socialmedia'),
        ('patients', '0005_auto_20210320_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Prescription Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('quantity', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('days', models.FloatField(default=0.0, verbose_name='Prescription Days')),
                ('morning', models.BooleanField(default=False, verbose_name='Morning')),
                ('afternoon', models.BooleanField(default=False, verbose_name='Afternoon')),
                ('evening', models.BooleanField(default=False, verbose_name='Evening')),
                ('night', models.BooleanField(default=False, verbose_name='Night')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(verbose_name='Record Date')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('attachment', models.FileField(blank=True, upload_to='File/Patient/MedicalRecords/', verbose_name='Attachment')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
