# Generated by Django 3.1.7 on 2021-03-22 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0004_socialmedia'),
        ('patients', '0007_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('review_title', models.CharField(blank=True, max_length=50, verbose_name='Review Title')),
                ('review_text', models.CharField(blank=True, max_length=150, verbose_name='Review Title')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('reply_text', models.CharField(max_length=150, verbose_name='Review Title')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikedReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.BooleanField(default=False, verbose_name='Recommend')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikedReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.BooleanField(default=False, verbose_name='Recommend')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
