# Generated by Django 3.1.7 on 2021-03-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_likedreply_likedreview_reply_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_title',
            new_name='title',
        ),
    ]
