# Generated by Django 3.1.7 on 2021-02-27 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Doctors', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('title', models.CharField(default='Dr.', max_length=200, verbose_name='Title')),
                ('phone_no', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('d_o_b', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('biography', models.CharField(blank=True, max_length=1000, verbose_name='Biography')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='County')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Town')),
                ('pricing', models.FloatField(default=0.0, verbose_name='Amount')),
                ('services', models.CharField(blank=True, max_length=1000, verbose_name='Services')),
                ('specialization', models.CharField(blank=True, max_length=1000, verbose_name='Specialization')),
                ('clinic', models.CharField(blank=True, max_length=100, verbose_name='Clinic')),
                ('clinic_address', models.CharField(blank=True, max_length=100, verbose_name='Clinic Address')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(max_length=500, upload_to='Image/Speciality', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateTimeField(verbose_name='Year')),
                ('registration', models.CharField(max_length=50, verbose_name='Registration')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=50, verbose_name='Membership')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50, verbose_name='Hospital Name')),
                ('start', models.DateTimeField(verbose_name='From')),
                ('finish', models.DateTimeField(blank=True, verbose_name='To')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50, verbose_name='Degree')),
                ('institute', models.CharField(max_length=50, verbose_name='College/Institute')),
                ('y_o_c', models.DateField(verbose_name='Year of Completion')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.speciality'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=50, verbose_name='Award')),
                ('year', models.DateTimeField(verbose_name='Year')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
