# Generated by Django 3.1.7 on 2021-03-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.DateField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='finish',
            field=models.DateField(blank=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.DateField(verbose_name='Year'),
        ),
    ]
